### ISSUE TITLE
Need to modify existing config for it to work with themite

### ISSUE THREAD

**Issue by LargeLlama** [dalesnail/themite#3]
The config file that I already had existing in my termite folder didn't have the [end-colors] phrase, causing an error within the `theme_swap` method, specifically, the line `end = content.index('\n[end-colors]')`

This raises an error where the substring `[end-colors]` isn't found.
I fixed this by manually adding it to the end of my existing file.

You could make a note of this in your README.md, or account for the instance where it isn't found by simply going to the end of the file.

**Comment by dalesnail** [comment]
I merged the pull request, but I may remove some of the comments, You're right that it needs some for sure. Also had to fix one thing in the print statement for main, needed to change it over to 'themite' rather than 'theme'. Awesome contribution though, the addition to list was very welcome!

**Comment by LargeLlama** [comment]
Thanks!
