### ISSUE TITLE
Font change doesn't work

### ISSUE THREAD

**Issue by LargeLlama** [dalesnail/themite#6]
I never really used the font change option, but apparently is doesn't work at all. Doesn't matter what I input, it just exits without making any changes to the file. 

A valid fix might be to remove the already existing `[options]` section, and replace it, or add an `[options]` to the top of the current config if it doesn't already exist. 
I'll try to get working on it.

**Comment by LargeLlama** [comment]
Update: am able to list fonts, have to add ability to change them

**Comment by dalesnail** [comment]
Font change is working fine for me even after puling new changes. Mind posting your config and a filepath to where you keep it?

**Comment by LargeLlama** [comment]
[config.txt](https://github.com/dalesnail/themite/files/1958808/config.txt)

here's my config, I keep it in ~/.config/termite/config

I'm working on a fix now, it's because it doesn't have an `[options]` section
I will make it so if no `[options]` section is written, one is made and a font line is added, otherwise we simply edit the current config.

EDIT - the file extension is .txt because that's how git wants it, the real one has no file extension

**Comment by dalesnail** [comment]
Ah gotcha, fair enough. I'd assumed the base config had a pre configured [options] section. That would be a good addition though, to add one if not seen. I'll work on a solution for that as well, so I can use for the urxvt side of things, and add it argparse.

**Comment by dalesnail** [comment]
Tested all the new things, they seem to be working great. Merged and using now. Will update the argparse later today. Thanks again for all the contributions man!
